DROP TABLE IF EXISTS Car;
CREATE TABLE [Car] ([id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,[ownerID] INTEGER NOT NULL,[make] VARCHAR NOT NULL,[model] VARCHAR,[year] INTEGER NOT NULL);
INSERT INTO Car(ownerID,make,model,year)  VALUES(1,"Honda","Civic",2000);
INSERT INTO Car(ownerID,make,model,year)  VALUES(3,"Honda","HR-V",2011);
INSERT INTO Car(ownerID,make,model,year)  VALUES(6,"Honda","CR-V",2001);
INSERT INTO Car(ownerID,make,model,year)  VALUES(5,"Honda","CR-V",2003);
INSERT INTO Car(ownerID,make,model,year)  VALUES(4,"Honda","Accord",2010);
INSERT INTO Car(ownerID,make,model,year)  VALUES(1,"Honda","Accord",2011);
INSERT INTO Car(ownerID,make,model,year)  VALUES(1,"Honda","Accord",2012);
INSERT INTO Car(ownerID,make,model,year)  VALUES(2,"Honda","CR-Z",2000);
INSERT INTO Car(ownerID,make,model,year)  VALUES(2,"Honda","CR-Z",2001);
INSERT INTO Car(ownerID,make,model,year)  VALUES(4,"Honda","CR-Z",2002);
INSERT INTO Car(ownerID,make,model,year)  VALUES(4,"Honda","CR-Z",2003);
INSERT INTO Car(ownerID,make,model,year)  VALUES(2,"Toyota","Corolla",2010);
INSERT INTO Car(ownerID,make,model,year)  VALUES(6,"Toyota","Corolla",2012);
INSERT INTO Car(ownerID,make,model,year)  VALUES(6,"Toyota","Corolla",2014);
INSERT INTO Car(ownerID,make,model,year)  VALUES(6,"Toyota","Prius",2006);
INSERT INTO Car(ownerID,make,model,year)  VALUES(5,"Toyota","Prius",2008);
INSERT INTO Car(ownerID,make,model,year)  VALUES(5,"Toyota","Prius",2010);
INSERT INTO Car(ownerID,make,model,year)  VALUES(4,"Toyota","Prius",2012);
INSERT INTO Car(ownerID,make,model,year)  VALUES(1,"Mercedes Benz","GLA-Class",2006);
INSERT INTO Car(ownerID,make,model,year)  VALUES(1,"Mercedes Benz","GLA-Class",2012);
INSERT INTO Car(ownerID,make,model,year)  VALUES(2,"Mercedes Benz","GLA-Class",2013);
INSERT INTO Car(ownerID,make,model,year)  VALUES(1,"Mercedes Benz","GLA-Class",2014);
INSERT INTO Car(ownerID,make,model,year)  VALUES(2,"Mercedes Benz","CLA-Class",2011);
INSERT INTO Car(ownerID,make,model,year)  VALUES(5,"Mercedes Benz","CLA-Class",2012);
INSERT INTO Car(ownerID,make,model,year)  VALUES(5,"Mercedes Benz","CLA-Class",2013);
INSERT INTO Car(ownerID,make,model,year)  VALUES(6,"Mercedes Benz","C-Class",2011);
INSERT INTO Car(ownerID,make,model,year)  VALUES(4,"Mercedes Benz","E-Class",2014);
INSERT INTO Car(ownerID,make,model,year)  VALUES(3,"Mercedes Benz","E-Class",2015);
INSERT INTO Car(ownerID,make,model,year)  VALUES(1,"Mercedes Benz","S-Class",2011);
INSERT INTO Car(ownerID,make,model,year)  VALUES(5,"Mercedes Benz","S-Class",2012);
INSERT INTO Car(ownerID,make,model,year)  VALUES(6,"Mercedes Benz","S-Class",2013);
INSERT INTO Car(ownerID,make,model,year)  VALUES(4,"Mercedes Benz","S-Class",2014);
INSERT INTO Car(ownerID,make,model,year)  VALUES(3,"BMW","5 Series",2014);
INSERT INTO Car(ownerID,make,model,year)  VALUES(3,"BMW","5 Series",2015);
INSERT INTO Car(ownerID,make,model,year)  VALUES(3,"BMW","5 Series",2016);
INSERT INTO Car(ownerID,make,model,year)  VALUES(6,"BMW","3 Series",2014);
INSERT INTO Car(ownerID,make,model,year)  VALUES(5,"BMW","3 Series",2015);
INSERT INTO Car(ownerID,make,model,year)  VALUES(6,"BMW","3 Series",2016);
INSERT INTO Car(ownerID,make,model,year)  VALUES(2,"BMW","X1",2012);
INSERT INTO Car(ownerID,make,model,year)  VALUES(2,"BMW","X1",2013);
INSERT INTO Car(ownerID,make,model,year)  VALUES(4,"BMW","X1",2014);
INSERT INTO Car(ownerID,make,model,year)  VALUES(1,"BMW","X1",2015);
INSERT INTO Car(ownerID,make,model,year)  VALUES(1,"BMW","X1",2016);

DROP TABLE IF EXISTS Owner;
CREATE TABLE [Owner] ([id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,[name] VARCHAR NOT NULL,[address] VARCHAR,[age] INTEGER NOT NULL);
INSERT INTO Owner(name,address,age) VALUES('julius maki','1103 calle de téllez bilbao, castilla y león 45960', 40);
INSERT INTO Owner(name,address,age) VALUES('adèle durand','8586 rue des chartreux créteil, seine-maritime 96368', 43);
INSERT INTO Owner(name,address,age) VALUES('owen fox','7178 samaritan dr santa maria, washington 11223', 50);
INSERT INTO Owner(name,address,age) VALUES('ralph gutierrez','5906 homestead rd fresno, north dakota 97237', 54);
INSERT INTO Owner(name,address,age) VALUES('basile gaillard','4355 place du 8 février 1962 perpignan, doubs 30283', 59);
INSERT INTO Owner(name,address,age) VALUES('ramon bravo','2270 calle de bravo murillo elche, región de murcia 82764', 60);

